# PetStore GraphQL Schema

"""
Represents a pet in the system
"""
type Pet {
  id: ID!
  name: String!
  tag: String
  friend: Pet
}

"""
Error response containing an error code and message
"""
type Error {
  code: Int!
  message: String!
}

"""
Response for paginated pet list
"""
type PetsResponse {
  pets: [Pet!]!
  nextPage: String
}

union PetsResult = PetsResponse | Error
union PetResult = Pet | Error

"""
Input type for creating a new pet
"""
input CreatePetInput {
  name: String!
  tag: String
}

type Query {
  """
  List all pets with optional pagination
  """
  infallibleListPets(limit: Int): PetsResponse!

  
  """
  Get information about a specific pet by ID
  """
  getPet(id: ID!): Pet
}


extend type Query {
  """
  Get information about a specific pet by ID, but may return an error
  """
  fallibleGetPet(id: ID!): PetResult!

  """
  List all pets with optional pagination, but may return an error
  """
  fallibleListPets(limit: Int): PetsResult!
}

type Mutation {
  """
  Create a new pet
  """
  createPet(input: CreatePetInput!): Pet!
  
  """
  Delete an existing pet by ID
  """
  deletePet(id: ID!): Boolean!
}
